version: "3.9"
services:
 #mongodb services 
 mongo_db:
   container_name: db_container
   image: mongo:latest
   restart: always
   ports:
      - 27017:27017
   volumes:
     - mongo_db:/data/db


# Node API services
 api:
  build: .
  ports:
    - 3000:4000
  volumes:
    - .:/usr/src/app
  environment:
    PORT: 4000
    DB_URL: mongodb://mongo_db:27017/ecomstore
    JWT_SECRET: thisismyjwtsecret
    JWT_EXPIRY: 3d
    COOKIE_TIME: 3
    CLOUDINARY_NAME: dffxeogta
    CLOUDINARY_API_KEY: 887258745392188
    CLOUDINARY_API_SECRET: 6BDYfqLs9wHrVXppgnCqlVJDa2A
  depends_on:
    - mongo_db
volumes:
  mongo_db: {}
  
   
    



  